apiVersion: v1
kind: Pod
metadata:
  name: test-helloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: HW-demo
    image: my-app/rhesb
    ports:
    - name: nodejs-port
      containerPort: 3000 
